version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/jowa
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=jowa
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"