services:
  - type: web
    name: jowa-ussd-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jowa-database
          property: connectionString
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false